import {
  ArrowRight,
  ArrowUpRight,
  Braces,
  CalendarDays,
  CircleUserRound,
  Eye,
  EyeOff,
  FileText,
  GitBranch,
  Globe2,
  Grid2X2,
  House,
  Link,
  type LucideIcon,
  Mail,
  Network,
  Rocket,
  SquareArrowOutUpRight,
  Triangle,
} from "lucide-react";

export const iconLibrary: Record<string, LucideIcon> = {
  arrowUpRight: ArrowUpRight,
  arrowRight: ArrowRight,
  email: Mail,
  globe: Globe2,
  person: CircleUserRound,
  grid: Grid2X2,
  openLink: Link,
  calendar: CalendarDays,
  home: House,
  eye: Eye,
  eyeOff: EyeOff,
  github: GitBranch,
  linkedin: Network,
  arrowUpRightFromSquare: SquareArrowOutUpRight,
  document: FileText,
  rocket: Rocket,
  javascript: Braces,
  nextjs: Triangle,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
